name: openim_common
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: 5.7.0
  get: 4.6.5
  dio: 5.0.2
  pretty_dio_logger: 1.3.1
  hive: 2.2.3
  hive_flutter: 1.1.0
  shared_preferences: 2.0.18
  sprintf: 7.0.0
  uuid: 3.0.7
  flutter_bugly: 0.4.4
  path_provider: 2.0.13
  android_path_provider: 0.3.0
  image_picker: 0.8.7
  flutter_easyloading: 3.0.5
  azlistview: 2.0.0
  lpinyin: 2.0.3
  rxdart: 0.27.7
  permission_handler: 10.2.0
  wechat_assets_picker: 8.4.0
  wechat_camera_picker: 3.8.0
  extended_image: 7.0.2
  country_picker: 2.0.20
  image_gallery_saver: 1.7.1
  file_picker: 5.2.6
  open_filex: 4.3.2
  lottie: 2.3.0
  qr_flutter: 4.1.0
  r_scan: 0.1.6+1
  qr_code_scanner: 1.0.1
  image_cropper: 3.0.1
  package_info_plus: 3.1.2
  search_keyword_text: 0.0.2
  animated_text_kit: 4.2.2
  flutter_local_notifications: 13.0.0
  flutter_app_badger: 1.5.0
  crypto: 3.0.2
  pull_to_refresh: 2.0.0
  url_launcher: 6.1.10
  common_utils: 2.1.0
  uri_to_file: 0.2.0
  map_launcher: 2.5.0+1
  flutter_map: 3.1.0
  latlong2: 0.8.1
  flutter_spinkit: 5.1.0
  percent_indicator: 4.2.3
  flutter_image_compress: 1.1.3
  app_installer: 1.1.0
  collection:
  flutter_datetime_picker: 1.5.1
  font_awesome_flutter: 10.4.0
  dart_date: 1.1.1
  video_compress: 3.1.2
  just_audio: 0.9.31
  flutter_inappwebview: 5.7.2+3
  vibration: 1.7.6
  getuiflut: 0.2.18
  scroll_to_index: 3.0.1
  flutter_screen_lock: 9.0.1
  local_auth: 2.1.6
  local_auth_android: 1.0.21
  local_auth_ios: 1.1.1
  gesture_password_widget: 2.0.1
  sound_mode: 2.0.2
  device_info_plus: 8.1.0
  visibility_detector: 0.4.0+2
  extended_text_field: 11.0.1
  extended_text: 10.0.1
  animate_do: 3.0.2
  emoji_picker_flutter: 1.5.2
  should_rebuild: 1.0.1
  record: 4.4.4
  mime: 1.0.4
  flutter_keyboard_visibility: 5.4.0
  rotated_corner_decoration: 2.1.0
  chewie: 1.4.0
  video_player: 2.6.0
  flutter_cache_manager: 3.3.0
  syncfusion_flutter_core: 21.1.38
  syncfusion_flutter_sliders: 21.1.38
  flutter_download_manager:
    git:
      url: https://github.com/hrxiang/flutter_download_manager.git
  flutter_openim_sdk: 3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
    - assets/anim/
    - assets/audio/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
